baseURL = 'https://eyoeltmichael.github.io/'
languageCode = 'en-us'
title = 'Eyoel TMichael'
theme = 'hugo-book'

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content.en'
  weight = 1

[params]
  enableGitInfo = true
  BookSection = 'docs'
  
  BookRepo = 'https://eyoeltmichael.github.io/eyoeltmichael'
  BookEditPath = 'edit/main'

  # BookTheme = 'dark'

  # BookMenuBundle = '/menu'
  BookPortableLinks = true
  BookToC = true
  BookServiceWorker = true
  BookTranslatedOnly = false
  BookSearch = true
